### ISSUE TITLE
Web UI to manage mockingjay

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server-two#11]
Try using HTMLX

https://htmx.org/docs/#introduction

## Acceptance criteria

HTML equivalents for all endpoints

- [x] View Configuration
- [ ] View match reports
- [ ] View specific report
- [ ] Form to add endpoint (the driver should use this in `Configure` rather than the HTTP API)
- [ ] Form to delete endpoint
- [ ] Form to edit endpoint

## TODOS

- [ ] Pass in the stub server URL so the path can be rendered in full in the table
- [x] Verify data in the table is correct
- [ ] Details/Summary for large bodies
- [ ] Sort by path

**Comment by quii** [comment]
Use https://missing.style
